#!/bin/sh
###
PROJECT=AMD_CANOVA

ENABLE="RPU_MODE_EXPLORER MULTI_CHAN_SUPPORT HAL_PCIE RPU_DMA_ZONE RPU_ACCESS_FULL_DDR RPU_SGI_SUPPORT SOC_AMD RPU_HPQM_SUPPORT"
DISABLE="RPU_MODE_LPW PERF_PROFILING RPU_SNAPSHOT PALLADIUM BB_LOOPBACK LOOPBACK DFS_TEST notyet WOWLAN RPU_SLEEP_SUPPORT RPU_SLEEP_SUPPORT_NEW BEACON_TIME_STAMP RPU_HARD_RESET_SUPPORT SOC_IMG_WHISPER SOC_ST RPU_RESTRICTED_DMA"
###

SCRIPTS_COMMON_PATH=./../../scripts/softmac/generate/generate_driver_common.sh
. $SCRIPTS_COMMON_PATH
generate_driver "$ENABLE" "$DISABLE"
##remove unnecessary files
rm -f $PWD/$PROJECT/src/hal_hostport.c
rm -rf $PWD/$PROJECT/fw_load/meta
rm -rf $PWD/$PROJECT/fw_load/mips/rompatching/
rm -rf $PWD/$PROJECT/shared_lpw

