#!/bin/sh
###
PROJECT=WHISPER
ENABLE="RPU_MODE_LPW KERNEL_VERSION_4_4 HAL_PCIE WOWLAN RPU_SGI_SUPPORT RPU_HARD_RESET_SUPPORT SOC_IMG DEV_BOARD_VCU108 RPU_RESTRICTED_DMA"
DISABLE="RPU_MODE_EXPLORER KERNEL_VERSION_4_1 KERNEL_VERSION_3_10 PERF_PROFILING MULTI_CHAN_SUPPORT BEACON_TIME_STAMP RPU_SNAPSHOT DFS_TEST BB_LOOPBACK PALLADIUM RPU_DMA_ZONE LOOPBACK notyet RUNTIME_PM RPU_ACCESS_FULL_DDR RPU_SLEEP_SUPPORT RPU_SLEEP_SUPPORT_NEW HPQM_SUPPORT DEV_BOARD_VCU118 HACK_SERDES_CONFIG SOC_AMD SOC_ST DEV_BOARD_VCU118"
###

SCRIPTS_COMMON_PATH=./../../scripts/softmac/generate/generate_driver_common.sh
. $SCRIPTS_COMMON_PATH
generate_driver "$ENABLE" "$DISABLE"
##remove unnecessary files
rm -rf $PWD/$PROJECT/fw_load/meta
rm -rf $PWD/$PROJECT/shared_exp
rm -rf $PWD/$PROJECT/src/hpqm_if.c
