#!/bin/sh
###
PROJECT=RK
ENABLE="RPU_MODE_LPW RPU_SERIES_4XT RPU_SERIES4_OR_LPW KERNEL_VERSION_3_10 SOC_RK RPU_ACCESS_FULL_DDR WOWLAN RPU_SLEEP_SUPPORT"
DISABLE="RPU_SERIES_4 RPU_MODE_EXPLORER RPU_SERIES4XT_AND_EXP KERNEL_VERSION_4_1 KERNEL_VERSION_4_4 SOC_X86 PERF_PROFILING MULTI_CHAN_SUPPORT BEACON_TIME_STAMP RPU_SNAPSHOT DFS_TEST BB_LOOPBACK PALLADIUM SOC_AMD SOC_EUROPA SOC_DANUBE RPU_DMA_ZONE LOOPBACK notyet RUNTIME_PM SOC_GF RPU_SGI_SUPPORT HPQM_SUPPORT SOC_AMD_VCU118 SOC_AMD_VCU108 HACK_SERDES_CONFIG"
###

SCRIPTS_COMMON_PATH=./../../scripts/softmac/generate/generate_driver_common.sh
. $SCRIPTS_COMMON_PATH
generate_driver "$ENABLE" "$DISABLE"
##remove unnecessary files
rm -rf $PWD/$PROJECT/fw_load/meta
rm -rf $PWD/$PROJECT/fw_load/mips/hostloader

